/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ChatSession = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'sourceUrl' : IDL.Text,
  'timestamp' : Time,
  'parsedChatJson' : IDL.Text,
});
export const ChatSessionInput = IDL.Record({
  'title' : IDL.Text,
  'sourceUrl' : IDL.Text,
  'parsedChatJson' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'fetchUrlContent' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getChatSession' : IDL.Func([IDL.Nat], [ChatSession], ['query']),
  'getTotalExports' : IDL.Func([], [IDL.Nat], ['query']),
  'listChatSessions' : IDL.Func([], [IDL.Vec(ChatSession)], ['query']),
  'saveChatSession' : IDL.Func([ChatSessionInput], [IDL.Nat], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ChatSession = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'sourceUrl' : IDL.Text,
    'timestamp' : Time,
    'parsedChatJson' : IDL.Text,
  });
  const ChatSessionInput = IDL.Record({
    'title' : IDL.Text,
    'sourceUrl' : IDL.Text,
    'parsedChatJson' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'fetchUrlContent' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getChatSession' : IDL.Func([IDL.Nat], [ChatSession], ['query']),
    'getTotalExports' : IDL.Func([], [IDL.Nat], ['query']),
    'listChatSessions' : IDL.Func([], [IDL.Vec(ChatSession)], ['query']),
    'saveChatSession' : IDL.Func([ChatSessionInput], [IDL.Nat], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };